export const USERNAME_OR_PASSWORD_NOT_MATCH = 'USERNAME_OR_PASSWORD_NOT_MATCH';
export const CAPTCHA_NOT_MATCH = 'CAPTCHA_NOT_MATCH';
export const USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS';
